# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newword.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from helpwindow import Ui_MainWindow
from PyQt5 import QtCore, QtGui, QtWidgets
from rule_conversion import make_new_nepali
from user_map import save_new_word

class Ui_MainWindow2(object):
    def setupUi(self, MainWindow):
        self.main=MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(679, 280)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(13)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.static_line = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.static_line.sizePolicy().hasHeightForWidth())
        self.static_line.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.static_line.setFont(font)
        self.static_line.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.static_line.setInputMask("")
        self.static_line.setText("")
        self.static_line.setAlignment(QtCore.Qt.AlignCenter)
        self.static_line.setObjectName("static_line")
        self.horizontalLayout.addWidget(self.static_line)
        self.helpButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helpButton.sizePolicy().hasHeightForWidth())
        self.helpButton.setSizePolicy(sizePolicy)
        self.helpButton.setMinimumSize(QtCore.QSize(41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.helpButton.setFont(font)
        self.helpButton.setStyleSheet("background:rgb(202, 198, 212);color:rgb(66, 77, 223);border-radius: 20px;padding-bottom:4px")
        self.helpButton.setDefault(False)
        self.helpButton.setFlat(False)
        self.helpButton.setObjectName("helpButton")
        self.horizontalLayout.addWidget(self.helpButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.generated1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.generated1.setFont(font)
        self.generated1.setScaledContents(False)
        self.generated1.setAlignment(QtCore.Qt.AlignCenter)
        self.generated1.setObjectName("generated1")
        self.verticalLayout.addWidget(self.generated1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mySpelling = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mySpelling.sizePolicy().hasHeightForWidth())
        self.mySpelling.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.mySpelling.setFont(font)
        self.mySpelling.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.mySpelling.setAlignment(QtCore.Qt.AlignCenter)
        self.mySpelling.setObjectName("mySpelling")
        self.horizontalLayout_2.addWidget(self.mySpelling)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.generated2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generated2.sizePolicy().hasHeightForWidth())
        self.generated2.setSizePolicy(sizePolicy)
        self.generated2.setMinimumSize(QtCore.QSize(0, 0))
        self.generated2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.generated2.setFont(font)
        self.generated2.setScaledContents(False)
        self.generated2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.generated2.setObjectName("generated2")
        self.horizontalLayout_2.addWidget(self.generated2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setIndent(5)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.static_line.textChanged[str].connect(self.suggest)
        self.pushButton.clicked.connect(self.save)
        self.mySpelling.textEdited.connect(self.removelabel)
        self.static_line.textEdited.connect(self.removelabel)

        self.helpButton.clicked.connect(self.helpdiag)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Add New Window"))
        self.static_line.setPlaceholderText(_translate("MainWindow", "Type a word here to make new unicode"))
        self.helpButton.setText(_translate("MainWindow", "?"))
        self.generated1.setText(_translate("MainWindow", "कागज"))
        self.mySpelling.setPlaceholderText(_translate("MainWindow", "Your spelling for this text"))
        self.label_4.setText(_translate("MainWindow", "="))
        self.generated2.setText(_translate("MainWindow", "कागज"))
        self.pushButton.setText(_translate("MainWindow", "SAVE"))
        self.label.setText(_translate("MainWindow", ""))
    
    def suggest(self, word):
        self.s=make_new_nepali(word)[0]
        self.generated1.setText(self.s)
        self.generated2.setText(self.s)
    
    def save(self):
        v=self.mySpelling.text()
        save_new_word(v,self.s)
        self.label.setText(v+" was mapped to "+self.s+" successfully!")
    
    def removelabel(self):
        self.label.setText("")

    def helpdiag(self):
        self.dg = QtWidgets.QMainWindow(self.main)
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.dg)
        self.dg.show()